pipeline {
    agent any
    stages {
        stage('Pull Node Image') {
            steps {
                sh 'docker pull meghnanookala511/node:16-alpine'
            }
        }
        stage('Pull Maven Image') {
            steps {
                sh 'docker pull meghnanookala511/maven:3.8.1-adoptopenjdk-11'
            }
        }
    }
}

